src/stepfunctions/inputs/placeholders.py, src/stepfunctions/steps/states.py, tests/unit/test_placeholders_with_steps.py, tests/unit/test_placeholders_with_workflows.py
Previously using the following syntax: `"ParamI": StateTwo.output()` failed with 
> ValueError: State 'StateThree' is using an illegal placeholder for the 'ParamI' parameter.
I've added a simple fix and extended the existing test cases so that `StepInput` placeholders behave similarly to `ExecutionInput`
AD
=> StepInput placeholder without key should resolve to $

src/stepfunctions/steps/__init__.py, src/stepfunctions/steps/service.py, tests/unit/test_service_steps.py
*Issue #, if available:* N/A
*Description of changes:* Adding SQS, SNS and DynamoDB support.
=> Add service integrations for SQS, SNS and DynamoDB

src/stepfunctions/steps/__init__.py, src/stepfunctions/steps/service.py, tests/unit/test_service_steps.py
*Description of changes:* Adding service integration for Amazon EMR.
=> Add service integration for Amazon EMR

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/15
S3Operations should be removed from ModelStep.
=> Delete S3Operations from ModelStep

tests/integ/__init__.py, tests/integ/test_inference_pipeline.py, tests/integ/test_sagemaker_steps.py, tests/integ/test_training_pipeline_estimators.py, tests/integ/test_training_pipeline_framework_estimator.py
Low timeout in integration tests (10 minutes) was causing frequent timeout exceptions in endpoint creation/deletion steps. Increased the tolerance.
=> Increase the integration test timeout.

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
*Issue #22:*
I've added additional optional arguments to the `TrainingStep` and `TransformStep` classes that will set the dictionary as properties that will then be passed through to the steps for execution.
=> feature: adding support for ExperimentConfig in training and transform

src/stepfunctions/steps/sagemaker.py, src/stepfunctions/template/pipeline/inference.py, tests/unit/test_pipeline.py, tests/unit/test_sagemaker_steps.py
*Issue #28*
Added support for reading debugger hook and rules from the estimator and writing to the API eg:
```
from sagemaker.debugger import Rule, rule_configs, DebuggerHookConfig, CollectionConfig
hook_config = DebuggerHookConfig(
s3_output_path='s3://{0}/{1}/output/debug'.format(bucket, prefix),
hook_parameters={
"save_interval": "1"
},
collection_configs=[
CollectionConfig("hyperparameters"),
CollectionConfig("metrics"),
CollectionConfig("predictions"),
CollectionConfig("labels"),
CollectionConfig("feature_importance")
]
)
xgb = sagemaker.estimator.Estimator(
debugger_hook_config=hook_config,
rules=[Rule.sagemaker(rule_configs.confusion(),
rule_parameters={
"category_no": "15",
"min_diag": "0.7",
"max_off_diag": "0.3",
"start_step": "17",
"end_step": "19"} …
```
=> Adding debug hook and rules configuration with tests

doc/conf.py
Sphinx docs are failing to build due to the error:
`No module named 'sagemaker.model_monitor'`
This docs build is failing because  'sagemaker.model_monitor' this is a recently imported from Sagemaker's Python SDK, but it was not added to the list of modules to be mocked by Sphinx. This PR fixes that issue.
*Tests*
Tested locally that the fix in this PR solves the docs build.
=> Adding 'sagemaker.model_monitor' to be mocked for Sphinx doc generation

src/stepfunctions/workflow/stepfunctions.py
This PR fixes the documentation for the definition parameter which expects a State or Chain and not a string.
Also add `Args:` to update() to correctly render in the doc page: https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/workflow.html#stepfunctions.workflow.Workflow.update.
=> Doc: fix definition parameter to State or Chain

src/stepfunctions/steps/states.py, tests/unit/test_steps.py
aws/aws-step-functions-data-science-sdk-python#45
This PR fixes the output null value in ResultPath to behave as described here: https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultpath.html#input-output-resultpath-null
The argument `result_path=None` in Python is going to be converted to `"ResultPath": null` in JSON.
I tested with Task, but it could be tested with any state type as I believe `"ResultPath": null` is a behavior available for any type.
Thank you for reviewing this!
=> Fix null value in ResultPath

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
Adding support for input_filter, output_filter and join_source to TransformStep
This is to add the support for the items listed above as they are already supported in the airflow transform_config API. (https://sagemaker.readthedocs.io/en/stable/airflow/sagemaker.workflow.airflow.html#transform-config)
=> adding support for filters to TransformStep

README.rst
The email was exposed to all crawlers and by changing "@" to " [at] " it's not easy to find anymore.
=> Hide email from crawlers

README.rst, doc/StepFunctionsWorkflowExecutionPolicy.json, doc/sagemaker.rst, requirements.txt, src/stepfunctions/steps/__init__.py, src/stepfunctions/steps/sagemaker.py, tests/data/sklearn_processing/preprocessor.py, tests/integ/conftest.py, tests/integ/test_sagemaker_steps.py, tests/unit/test_sagemaker_steps.py
#20 
Step Functions has added SageMaker Processing Job as the new service integration, we want to introduce `ProcessingStep` to use this functionality.
=> [Feature] Introduce ProcessingStep to use SageMaker Processing Job

requirements.txt, setup.py
This sdk is not working with sagemaker sdk v2, when running tests lot of errors are displayed (like the following) : 
``` 
______________________________________________________________________________________________ ERROR at setup of test_model_step_creation ______________________________________________________________________________________________
@pytest.fixture
def pca_model():
model_data = 's3://sagemaker/models/pca.tar.gz'
return Model(
model_data=model_data,
image=PCA_IMAGE,
role=EXECUTION_ROLE,
>           name='pca-model'
)
E       TypeError: __init__() got an unexpected keyword argument 'image'
tests/unit/test_sagemaker_steps.py:121: TypeError
``` 
So while waiting for sagemaker v2 compatibility, what about limiting version so that tests can succeed just by following README …
=> Limit sagemaker sdk v2 version dependency

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
*Issue #, if available:* #81 
* If the debug parameter for an estimator is set to `False`, we will not try to add the `DebugHookConfig` parameter for the `CreateTrainingJob` API request.
=> Support boolean False for debugger_hook_config parameter

tests/integ/test_training_pipeline_estimators.py
* Integration test for `TrainingPipeline` is failing due to the 2 new response parameters `inputDetails` and `outputDetails` from [DescribeExecution API](https://docs.aws.amazon.com/step-functions/latest/apireference/API_DescribeExecution.html#API_DescribeExecution_ResponseSyntax) that were previously unexpected.
=> Fixing failing integ test due to new DescribeExecution response params

src/stepfunctions/steps/compute.py, src/stepfunctions/steps/fields.py, src/stepfunctions/steps/service.py, src/stepfunctions/steps/states.py, tests/unit/test_steps.py
- Add support for dynamic timeout and heartbeat in Task state
- Add a simple test for this PR https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/103
=>  Add support for dynamic timeout and heartbeat in Task state

CONTRIBUTING.md
- Updated git checkout command to checkout main (and not master). 
- Reordered unit test steps: pip install must be done inside the project folder.
=> documentation: Updated git checkout command and reorder unit test steps

src/stepfunctions/steps/compute.py, src/stepfunctions/steps/integration_resources.py, src/stepfunctions/steps/sagemaker.py, src/stepfunctions/steps/service.py, src/stepfunctions/steps/utils.py, tests/integ/conftest.py, tests/integ/test_state_machine_definition.py, tests/unit/test_compute_steps.py, tests/unit/test_pipeline.py, tests/unit/test_sagemaker_steps.py, tests/unit/test_service_steps.py, tests/unit/test_steps.py, tests/unit/test_steps_utils.py
*Issue #, if available:* #120
*Update:*
Resolve previous comments. 
Use boto3 patch mock for unit tests. 
Use f-string for string building.
Create arn builder for providing integration resource arn.
Create tests for arn builder.
*Test:*
All unit tests and integ tests passed.
Support different aws partitions when SDK providing resource arns. Partitions will be determined by boto3 client session running region.
Available regions are based on SFN regional availability.
There are formatting changes for test_steps.py which done by IDE. They are valid changes and will not have functionality impact.
*Test:*
Created new unit under test_steps suite. All units tests passed.
All integration tests passed in both `us-east-1` and `cn-north-1` using test account.
By submitting …
=> fix: make arns of all task resources aws-partition aware

README.rst, src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
`Hyperparameters` can be specified in the `estimator` object and `hyperparameters` property.
Both of which are taken in the constructor of the `TrainingStep` class.
The current behaviour drops any hyperparameters that were specified in the estimator if the property
is set in the `TrainingStep` constructor. This is undesirable as the estimators often specify algorithm specific hyperparameters out of the box that we don't want to drop.
This change merges the hyperparameters in the constructor as well as the estimator that is used in `TrainingStep`.
If there are duplicate keys, the hyperparameters specified in the constructor will be used.
Closes #99, #72
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> fix: supplying hyperparameters to training step constructor drops hyperparameters specified in estimator

CONTRIBUTING.md
Added instructions to set up PyCharm for running and debugging tests locally.
---
=> docs: Add setup instructions to run/debug tests locally

src/stepfunctions/workflow/cloudformation.py, src/stepfunctions/workflow/stepfunctions.py, tests/unit/test_workflow.py
*Issue #, if available:* #107
Make it possible to provide a custom description to the cloud formation template when calling get_cloudformation_template()
=> feat: Add custom description for CloudFormation template

tests/integ/__init__.py, tests/integ/test_sagemaker_steps.py
Currently, we observe a few different failures that occur during integration tests, which get
executed as a part of the PR build as well as pushes to branches.
`createModel` and `createEndpoint` particularly see failures most frequently and they are
primarily:
* Rate exceeded  - `ThrottlingException`.
This change defines a default retry strategy that makes 5 attempts, over an interval of 5
seconds, which backs off with a multiplier of 2. The methodology behind this strategy is
naive and  may need some calibration. It should reduce the frequency of failures in the
short term.
We can adjust  the retry strategy as we go and expand to something more API specific as
the need arises.
* ran integ tests a few times locally - ensured they had the retry in the ASL definition and
executed through …
=> chore: add retry to SageMaker steps in integration tests

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
*Issue #, if available:* #152
A breaking change was introduced in V2.2.0 where it was no longer possible to use Placeholders as input for `hyperparameters` in TrainingStep.
With this solution, TrainingStep `hyperparameters` will be compatible with Placeholders with the same behaviour as in V2.1.0: if a Placeholder is provided as input to `hyperparameters` in TrainingStep constructor, the estimator hyperparameters are overwritten
A feature request to be able to merge the Placeholder hyperparameters was made in #152, which will be addressed in another PR.
=> fix: Support placeholders for hyperparameters passed to TrainingStep

src/stepfunctions/steps/sagemaker.py, tests/unit/test_sagemaker_steps.py
*Issue #, if available:* #82
**1. fix: environment variables are overwritten and not passed through to SageMaker ModelStep**
- The environment variables are not passed from the model to ModelStep parameters (they are overwritten [here](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/main/src/stepfunctions/steps/sagemaker.py#L296)) for models without instance type (models other than [sagemake.model.FrameworkModel](https://sagemaker.readthedocs.io/en/stable/api/inference/model.html?highlight=model#sagemaker.model.FrameworkModel))
- With this change, the Model env parameters are passed to the ModelStep.
*New bug uncovered*: 
**2. fix: env variables defined in the Estimator are not translated to Model when calling …
=> fix: environment variables specified in Model or Estimator are not passed through to SageMaker ModelStep

src/stepfunctions/steps/sagemaker.py, tests/integ/test_sagemaker_steps.py, tests/unit/test_sagemaker_steps.py
Add support to define Hyperparameters Tuning parameters dynamically using placeholders
Fixes #85 
Currently, it is not possible to use placeholders for Sagemaker Hyperparameters Tuning properties. The properties cannot be defined dynamically, as they need to be defined in the HyperparameterTuner which does not accept placeholders.
This change makes it possible to use placeholders for HyperparameterTuner properties by using the parameters field that are passed down from the TuningStep.
Use the `parameters` field that is compatible with placeholders to define TuningStep properties.
Merge the parameters that were generated from the [HyperparameterTuner](https://sagemaker.readthedocs.io/en/stable/api/training/tuner.html) with the input parameters:
- The input parameters will overwrite the …
=> feat: Support placeholders for TuningStep

src/stepfunctions/steps/service.py, tests/unit/test_service_steps.py
Update AWS Glue Databrew service integration to use `integration_pattern` input instead or `wait_for_completion` flag.
Fixes #(issue) (N/A)
This change is necessary for consistency with the new service integration implementation pattern introduced in [commit](https://github.com/aws/aws-step-functions-data-science-sdk-python/commit/f9e63b312f543954c663e305fd5eedd9b2cdd360) (Add support for Nested Step Functions) that uses the `integration_pattern` arg in the step constructor to build the resource.
Support for AWS Glue Databrew service integration was added in this [commit](https://github.com/aws/aws-step-functions-data-science-sdk-python/commit/ac652ab84ff74284ce996097c7c857e642043a3b), but not **released yet**.
A later [commit](https://github.com/aws/aws-step-functions-data-science-sdk-pyt …
=> refactor: Update AWS Glue Databrew StartJobRun step to use integration pattern input

doc/services.rst, src/stepfunctions/steps/sagemaker.py, src/stepfunctions/steps/service.py
Fix docstring links and format 
Fixes #(issue) - **N/A**
There are a few issues with certain docstrings links and format
Generating the documentation locally with sphynx returned the following warnings 
```
/README.rst:: WARNING: image file not readable: doc/images/create.png
/README.rst:: WARNING: image file not readable: doc/images/execute.png
/src/stepfunctions/steps/sagemaker.py:docstring of stepfunctions.steps.sagemaker.TrainingStep:26: WARNING: Unexpected indentation.
/src/stepfunctions/steps/sagemaker.py:docstring of stepfunctions.steps.sagemaker.TrainingStep:27: WARNING: Block quote ends without a blank line; unexpected unindent.
/src/stepfunctions/steps/sagemaker.py:docstring of stepfunctions.steps.sagemaker.TrainingStep:39: WARNING: Unknown target name: …
```
=> docs: Fix doc format and links
